# Copyright (C) 2026 Boris Shkylnikov
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of Vox Bee.
#
# Vox Bee is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# Vox Bee is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Vox Bee. If not, see <https://www.gnu.org/licenses/>.

TRANSLATIONS = {
    "ru": {
        "tray.turn_off": "⏹ Выключить",
        "tray.turn_on": "🎤 Включить",
        "tray.auto_mode_on": "✅ Авто-режим (VAD)",
        "tray.auto_mode_off": "🔲 Авто-режим (VAD)",
        "tray.gpu_on": "✅ GPU (CUDA)",
        "tray.gpu_off": "🔲 GPU — сейчас CPU",
        "tray.microphone": "🎤 Микрофон: {name}",
        "tray.model": "🧠 Модель: {name}",
        "tray.mouse_step": "🖱️ Шаг мыши: {step}px",
        "tray.settings": "⚙️ Настройки...",
        "tray.exit": "❌ Выход",
        "tray.record_button": "🎯 Кнопка записи: {label}",
        "tray.current": "  ✅ Сейчас: {label}",
        "tray.assign_button": "  🔴 Назначить кнопку...",
        "tray.reset_middle": "  🔄 Сбросить на колёсико",
        "tray.hold_modifier": "  💡 Зажмите модификатор + кнопку мыши",
        "tray.assign_title": "Назначить кнопку записи",
        "tray.assign_hint": "Нажмите нужную кнопку мыши\nили клавишу клавиатуры",
        "tray.assign_modifiers": "Можно с зажатым Ctrl / Alt / Shift",
        "tray.waiting": "⏳ Ожидание...",
        "common.save": "💾 Сохранить",
        "common.cancel": "Отмена",
        "tray.key_warning": "⚠️ Клавиша '{key}' может мешать печати!",
        "tray.button_title": "VoxBee — Кнопка: {label}",
        "tray.scripts": "🚀 Скрипты",
        "tray.scripts_count": "🚀 Скрипты ({count})",
        "tray.script": "🚀 Скрипт: {name}",
        "tray.script_manager": "⚙️ Управление скриптами...",
        "tray.scripts_folder": "📂 Папка скриптов",
        "common.reload": "🔄 Перезагрузить",
        "tray.no_scripts": "  (нет скриптов)",
        "tray.load_error": "  (ошибка загрузки)",
        "tray.warmup_on": "✅ Модель загружена (быстрое распознавание)",
        "tray.warmup_off": "🔲 Модель выгружена (экономия памяти)",
        "tray.text_fix_on": "✏️ Исправление текста: ВКЛ",
        "tray.text_fix_off": "✏️ Исправление текста: ВЫКЛ",
        "tray.fix_all": "{prefix} Исправлять текст (всё)",
        "tray.fix_hallucinations": "Удалять галлюцинации",
        "tray.fix_dictionary": "Словарь терминов (встроенный)",
        "tray.fix_user_dictionary": "Словарь пользователя ({count} слов)",
        "tray.fix_repetitions": "Удалять повторы",
        "tray.fix_punctuation": "Пунктуация и заглавные",
        "tray.reload_dictionary": "  🔄 Перезагрузить словарь",
        "tray.dictionary_folder": "  📂 Папка словаря",
        "tray.commands_off": "🎯 Команды: ВЫКЛ",
        "tray.commands": "🎯 Команды",
        "tray.commands_count": "🎯 Команды ({count})",
        "tray.recognize_commands": "{prefix} Распознавать команды",
        "tray.reload_commands": "🔄 Перезагрузить команды и алиасы",
        "tray.triggers_count": "  ℹ️ Триггеров: {count}",
        "tray.settings_folder": "📂 Папка настроек",
        "tray.commands_json": "  💡 commands.json — команды",
        "tray.aliases_json": "  💡 aliases.json — алиасы",
        "tray.refresh_list": "🔄 Обновить список",
        "tray.no_microphones": "(нет микрофонов)",
        "tray.best_available": "Лучшая доступная",
        "tray.no_models": "(модели не найдены)",
        "tray.off": "VoxBee — ВЫКЛ",
        "tray.ready": "VoxBee — Готов",
        "tray.recording": "VoxBee — ЗАПИСЬ",
        "tray.short_speech_on": "✅ Короткая речь (да/окей)",
        "tray.short_speech_off": "🔲 Короткая речь (да/окей)",
        "tray.noise_on": "✅ Шумоподавление",
        "tray.noise_off": "🔲 Шумоподавление",
        "tray.show_recognition_on": "✅ Показывать распознанное",
        "tray.show_recognition_off": "🔲 Показывать распознанное",
        "tray.math_on": "✅ Режим математики",
        "tray.math_off": "🔲 Режим математики",
        "tray.grid_on": "✅ Показать сетку",
        "tray.grid_off": "🔲 Показать сетку",
        "tray.autostart_on": "✅ Автозапуск",
        "tray.autostart_off": "🔲 Автозапуск",
        "tray.logging_on": "📝 Логирование: ВКЛ",
        "tray.logging_off": "📝 Логирование: ВЫКЛ",
        "tray.write_log": "{prefix} Записывать лог",
        "tray.logs_default": "logs/ (по умолчанию)",
        "tray.select_folder": "  📂 Выбрать папку...",
        "tray.reset_default": "  🔄 Сбросить на стандартную",
        "tray.open_log_folder": "  📁 Открыть папку логов",
        "tray.focus_points": "📍 Точки фокуса",
        "tray.focus_points_count": "📍 Точки фокуса ({count})",
        "tray.no_focus_points": "  (нет сохранённых точек)",
        "tray.focus_hint_save": "💡 Alt+Shift+1..9 — сохранить точку",
        "tray.focus_hint_voice": "💡 Голос: 'фокус 1' или голосовое имя",
        "tray.goto": "  ➡️ Перейти",
        "tray.voice_names": "  🏷️ Голосовые имена...",
        "common.delete": "  🗑️ Удалить",
        "tray.reset_all_points": "  🗑️ Сбросить все точки",
        "tray.voice_names_title": "Голосовые имена — Точка {slot}",
        "tray.voice_commands_title": "Точка {slot} — Голосовые команды",
        "tray.voice_commands_hint": "Через запятую. Пример: гугл, хром, браузер",
        "tray.language": "🌐 Язык",
        "tray.language_ru": "✅ Русский",
        "tray.language_en": "🔲 Английский",
        "tray.language_ru_off": "🔲 Русский",
        "tray.language_en_on": "✅ Английский",
        "tray.about": "ℹ️ О программе",

        
        "scripts.title": "VoxBee — Скрипты",
        "scripts.title_bar": "🚀 Управление скриптами",
        "scripts.list": "Список скриптов",
        "scripts.add": "➕ Добавить",
        "scripts.edit": "✏️ Редактировать",
        "scripts.delete": "🗑️ Удалить",
        "scripts.toggle": "⏯ Вкл/Выкл",
        "scripts.folder": "📂 Открыть папку",
        "scripts.delete_title": "Удалить скрипт",
        "scripts.delete_confirm": "Удалить скрипт «{name}»?",
        "scripts.add_title": "Добавить скрипт",
        "scripts.edit_title": "Редактировать скрипт",
        "scripts.add_title_bar": "➕ Добавить скрипт",
        "scripts.edit_title_bar": "✏️ Редактировать скрипт",
        "scripts.name": "Название:",
        "scripts.path": "Путь к файлу:",
        "scripts.voice_commands": "Голосовые команды:",
        "scripts.voice_hint": "Каждая команда — с новой строки",
        "scripts.select_script": "Выберите скрипт",
        "scripts.error": "Ошибка",
        "scripts.warn_name": "Введите название скрипта.",
        "scripts.warn_path": "Укажите путь к файлу скрипта.",
        "scripts.warn_triggers": "Добавьте хотя бы одну голосовую команду.",

        "settings.title": "VoxBee — Настройки",
        "settings.recognition": "Распознавание",
        "settings.auto_mode": "Авто-режим (VAD)",
        "settings.gpu": "GPU (CUDA)",
        "settings.microphone": "Микрофон:",
        "settings.model": "Модель:",
        "settings.short_speech": "Короткая речь (да/окей)",
        "settings.keep_model": "Держать модель в памяти (быстрое распознавание)",
        "settings.noise": "Шумоподавление",
        "settings.text_processing": "Обработка текста",
        "settings.fix_all": "Исправлять текст (всё)",
        "settings.fix_hallucinations": "  Удалять галлюцинации",
        "settings.fix_dictionary": "  Словарь терминов (встроенный)",
        "settings.fix_user_dictionary": "  Словарь пользователя",
        "settings.fix_repetitions": "  Удалять повторы",
        "settings.fix_punctuation": "  Пунктуация и заглавные",
        "settings.reload_dictionary": "🔄 Перезагрузить словарь",
        "settings.recognize_commands": "Распознавать команды",
        "settings.reload_commands": "🔄 Перезагрузить команды и алиасы",
        "settings.interface": "Интерфейс",
        "settings.show_recognition": "Показывать распознанный текст (popup)",
        "settings.mouse_step": "Шаг мыши (px):",
        "settings.record_button": "Кнопка записи:",
        "settings.assign": "Назначить...",
        "settings.reset": "Сбросить",
        "settings.middle_mouse": "Колёсико",
        "settings.not_selected": "(не выбран)",
        "settings.select_script_title": "Выберите скрипт",
        "settings.all_scripts": "Все скрипты",
        "settings.python_files": "Python файлы",
        "settings.batch_files": "Batch файлы",
        "settings.all_files": "Все файлы",
        "settings.system": "Система",
        "settings.language": "Язык:",
        "settings.write_log": "Записывать лог",
        "settings.log_folder": "Папка логов:",
        "settings.logs_default": "logs/ (по умолчанию)",
        "settings.select_log_folder": "Выберите папку для логов",
        "settings.autostart": "Автозапуск с Windows",
        "settings.about": "О программе",
        "common.close": "Закрыть",
        "about.title": "VoxBee — О программе",
        "about.heading": "VoxBee",
        "about.subtitle": "Голосовой ввод, команды и управление мышью",
        "about.body": "🐝 VoxBee\n\nГолос, команды, управление компьютером и немного магии повседневной работы ✨\n\nVoxBee создан как умный и практичный настольный помощник:\nчтобы текст появлялся быстрее ⌨️\nкоманды выполнялись проще ⚡\nа работа за компьютером ощущалась легче, точнее и приятнее 🎯\n\nЭто не просто программа.\nЭто инструмент, который берёт на себя рутину, экономит движения, сохраняет темп и помогает сосредоточиться на главном 🧠💛\n\nАвтор проекта — Борис Шкыльников,\nон же Секретный агент 007 🕵️‍♂️🔥\n\nИ, конечно, отдельное спасибо моей семье за поддержку. 🙏💛\nАлине — моей жене 🌷\nАлександре — моей дочери 🌟\nАлександру — моему брату 🤝\n\nСделано с вниманием к деталям и уважением ко времени пользователя 🐝✨\n\nGitHub проекта:\nhttps://github.com/boris-agent007/Voxbee",
        "about.site": "GitHub",
        "about.docs": "README",
        "about.support": "Issues",
        "language.russian": "Русский",
        "language.english": "English",
    },
    "en": {
        "tray.turn_off": "⏹ Turn off",
        "tray.turn_on": "🎤 Turn on",
        "tray.auto_mode_on": "✅ Auto mode (VAD)",
        "tray.auto_mode_off": "🔲 Auto mode (VAD)",
        "tray.gpu_on": "✅ GPU (CUDA)",
        "tray.gpu_off": "🔲 GPU — currently CPU",
        "tray.microphone": "🎤 Microphone: {name}",
        "tray.model": "🧠 Model: {name}",
        "tray.mouse_step": "🖱️ Mouse step: {step}px",
        "tray.settings": "⚙️ Settings...",
        "tray.exit": "❌ Exit",
        "tray.record_button": "🎯 Record button: {label}",
        "tray.current": "  ✅ Current: {label}",
        "tray.assign_button": "  🔴 Assign button...",
        "tray.reset_middle": "  🔄 Reset to middle mouse",
        "tray.hold_modifier": "  💡 Hold modifier + mouse button",
        "tray.assign_title": "Assign record button",
        "tray.assign_hint": "Press the target mouse button\nor keyboard key",
        "tray.assign_modifiers": "You can hold Ctrl / Alt / Shift",
        "tray.waiting": "⏳ Waiting...",
        "common.save": "💾 Save",
        "common.cancel": "Cancel",
        "tray.key_warning": "⚠️ Key '{key}' may interfere with typing!",
        "tray.button_title": "VoxBee — Button: {label}",
        "tray.scripts": "🚀 Scripts",
        "tray.scripts_count": "🚀 Scripts ({count})",
        "tray.script": "🚀 Script: {name}",
        "tray.script_manager": "⚙️ Script manager...",
        "tray.scripts_folder": "📂 Scripts folder",
        "common.reload": "🔄 Reload",
        "tray.no_scripts": "  (no scripts)",
        "tray.load_error": "  (load error)",
        "tray.warmup_on": "✅ Model loaded (fast recognition)",
        "tray.warmup_off": "🔲 Model unloaded (save memory)",
        "tray.text_fix_on": "✏️ Text fixing: ON",
        "tray.text_fix_off": "✏️ Text fixing: OFF",
        "tray.fix_all": "{prefix} Fix text (all)",
        "tray.fix_hallucinations": "Remove hallucinations",
        "tray.fix_dictionary": "Built-in terms dictionary",
        "tray.fix_user_dictionary": "User dictionary ({count} words)",
        "tray.fix_repetitions": "Remove repetitions",
        "tray.fix_punctuation": "Punctuation and capitalization",
        "tray.reload_dictionary": "  🔄 Reload dictionary",
        "tray.dictionary_folder": "  📂 Dictionary folder",
        "tray.commands_off": "🎯 Commands: OFF",
        "tray.commands": "🎯 Commands",
        "tray.commands_count": "🎯 Commands ({count})",
        "tray.recognize_commands": "{prefix} Recognize commands",
        "tray.reload_commands": "🔄 Reload commands and aliases",
        "tray.triggers_count": "  ℹ️ Triggers: {count}",
        "tray.settings_folder": "📂 Settings folder",
        "tray.commands_json": "  💡 commands.json — commands",
        "tray.aliases_json": "  💡 aliases.json — aliases",
        "tray.refresh_list": "🔄 Refresh list",
        "tray.no_microphones": "(no microphones)",
        "tray.best_available": "Best available",
        "tray.no_models": "(no models found)",
        "tray.off": "VoxBee — OFF",
        "tray.ready": "VoxBee — Ready",
        "tray.recording": "VoxBee — Recording",
        "tray.short_speech_on": "✅ Short speech (yes/okay)",
        "tray.short_speech_off": "🔲 Short speech (yes/okay)",
        "tray.noise_on": "✅ Noise suppression",
        "tray.noise_off": "🔲 Noise suppression",
        "tray.show_recognition_on": "✅ Show recognition",
        "tray.show_recognition_off": "🔲 Show recognition",
        "tray.math_on": "✅ Math mode",
        "tray.math_off": "🔲 Math mode",
        "tray.grid_on": "✅ Show grid",
        "tray.grid_off": "🔲 Show grid",
        "tray.autostart_on": "✅ Autostart",
        "tray.autostart_off": "🔲 Autostart",
        "tray.logging_on": "📝 Logging: ON",
        "tray.logging_off": "📝 Logging: OFF",
        "tray.write_log": "{prefix} Write log",
        "tray.logs_default": "logs/ (default)",
        "tray.select_folder": "  📂 Select folder...",
        "tray.reset_default": "  🔄 Reset to default",
        "tray.open_log_folder": "  📁 Open log folder",
        "tray.focus_points": "📍 Focus points",
        "tray.focus_points_count": "📍 Focus points ({count})",
        "tray.no_focus_points": "  (no saved points)",
        "tray.focus_hint_save": "💡 Alt+Shift+1..9 — save point",
        "tray.focus_hint_voice": "💡 Voice: 'focus 1' or a voice name",
        "tray.goto": "  ➡️ Go to",
        "tray.voice_names": "  🏷️ Voice names...",
        "common.delete": "  🗑️ Delete",
        "tray.reset_all_points": "  🗑️ Reset all points",
        "tray.voice_names_title": "Voice names — Point {slot}",
        "tray.voice_commands_title": "Point {slot} — Voice commands",
        "tray.voice_commands_hint": "Comma-separated. Example: google, chrome, browser",
        "tray.language": "🌐 Language",
        "tray.language_ru": "✅ Russian",
        "tray.language_en": "🔲 English",
        "tray.language_ru_off": "🔲 Russian",
        "tray.language_en_on": "✅ English",
        "tray.about": "ℹ️ About",

        
        "scripts.title": "VoxBee — Scripts",
        "scripts.title_bar": "🚀 Script Manager",
        "scripts.list": "Scripts list",
        "scripts.add": "➕ Add",
        "scripts.edit": "✏️ Edit",
        "scripts.delete": "🗑️ Delete",
        "scripts.toggle": "⏯ Enable/Disable",
        "scripts.folder": "📂 Open folder",
        "scripts.delete_title": "Delete script",
        "scripts.delete_confirm": "Delete script \"{name}\"?",
        "scripts.add_title": "Add script",
        "scripts.edit_title": "Edit script",
        "scripts.add_title_bar": "➕ Add script",
        "scripts.edit_title_bar": "✏️ Edit script",
        "scripts.name": "Name:",
        "scripts.path": "File path:",
        "scripts.voice_commands": "Voice commands:",
        "scripts.voice_hint": "One command per line",
        "scripts.select_script": "Select script",
        "scripts.error": "Error",
        "scripts.warn_name": "Enter the script name.",
        "scripts.warn_path": "Specify the path to the script file.",
        "scripts.warn_triggers": "Add at least one voice command.",

        "settings.title": "VoxBee — Settings",
        "settings.recognition": "Recognition",
        "settings.auto_mode": "Auto mode (VAD)",
        "settings.gpu": "GPU (CUDA)",
        "settings.microphone": "Microphone:",
        "settings.model": "Model:",
        "settings.short_speech": "Short speech (yes/okay)",
        "settings.keep_model": "Keep model in memory (fast recognition)",
        "settings.noise": "Noise suppression",
        "settings.text_processing": "Text processing",
        "settings.fix_all": "Fix text (all)",
        "settings.fix_hallucinations": "  Remove hallucinations",
        "settings.fix_dictionary": "  Built-in terms dictionary",
        "settings.fix_user_dictionary": "  User dictionary",
        "settings.fix_repetitions": "  Remove repetitions",
        "settings.fix_punctuation": "  Punctuation and capitalization",
        "settings.reload_dictionary": "🔄 Reload dictionary",
        "settings.recognize_commands": "Recognize commands",
        "settings.reload_commands": "🔄 Reload commands and aliases",
        "settings.interface": "Interface",
        "settings.show_recognition": "Show recognized text (popup)",
        "settings.mouse_step": "Mouse step (px):",
        "settings.record_button": "Record button:",
        "settings.assign": "Assign...",
        "settings.reset": "Reset",
        "settings.middle_mouse": "Middle Mouse",
        "settings.not_selected": "(not selected)",
        "settings.select_script_title": "Select script",
        "settings.all_scripts": "All scripts",
        "settings.python_files": "Python files",
        "settings.batch_files": "Batch files",
        "settings.all_files": "All files",
        "settings.system": "System",
        "settings.language": "Language:",
        "settings.write_log": "Write log",
        "settings.log_folder": "Log folder:",
        "settings.logs_default": "logs/ (default)",
        "settings.select_log_folder": "Select log folder",
        "settings.autostart": "Autostart with Windows",
        "settings.about": "About",
        "common.close": "Close",
        "about.title": "VoxBee — About",
        "about.heading": "VoxBee",
        "about.subtitle": "Voice input, voice commands, and mouse control",
        "about.body": "🐝 VoxBee\n\nVoice, commands, computer control, and a little everyday magic ✨\n\nVoxBee was created as a smart and practical desktop assistant:\nto make text appear faster ⌨️\ncommands run more easily ⚡\nand everyday work feel lighter, sharper, and more enjoyable 🎯\n\nThis is not just an app.\nIt is a tool that takes on routine work, saves movement, keeps your pace, and helps you stay focused on what matters most 🧠💛\n\nCreated by Boris Shkylnikov,\nalso known as Secret Agent 007 🕵️‍♂️🔥\n\nAnd of course, special thanks to my family for their support 🙏💛\nTo Alina, my wife 🌷\nTo Alexandra, my daughter 🌟\nTo Alexander, my brother 🤝\n\nMade with attention to detail and respect for the user's time 🐝✨\n\nProject GitHub:\nhttps://github.com/boris-agent007/Voxbee",
        "about.site": "GitHub",
        "about.docs": "README",
        "about.support": "Issues",
        "language.russian": "Русский",
        "language.english": "English",
    },
}


def tr(key, lang="ru", **kwargs):
    lang_map = TRANSLATIONS.get(lang, TRANSLATIONS["ru"])
    text = lang_map.get(key, TRANSLATIONS["ru"].get(key, key))
    return text.format(**kwargs)
